### ISSUE TITLE
Implement Form input according to spec here: https://www.figma.com/file/Nl3P6SFC7UIHYszh4piNZQ/Boba?node-id=83%3A0

### ISSUE THREAD

**Issue by essential-randomness** [essential-randomness/bobaboard-ui#18]
- [ ] restyling of `common/Input.tsx` in bobaboard-ui: https://github.com/essential-randomness/bobaboard-ui/blob/master/src/common/Input.tsx
- [ ] Implement limited-length input (character limit)
- [ ] Implement error label

Note: while there's a text area input in the specs, that shouldn't be implemented.

**Comment by smartgru** [comment]
@essential-randomness   
border-radius for input is missing in design
